name: databricks-teacher
organization: okube
description: Lakehouse - Databricks Teacher
backend: pulumi
pulumi:
  config:
    databricks:host: ${vars.DATABRICKS_HOST}
    databricks:azure_client_id: ${vars.AZURE_CLIENT_ID}
    databricks:azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
    databricks:azure_tenant_id: ${vars.AZURE_TENANT_ID}
resources:
  databricks_notebooks: ${include.resources/notebooks.yaml}
  databricks_workspacefiles: ${include.resources/workspacefiles.yaml}
#  databricks_sqlqueries: ${include.resources/sqlqueries.yaml}
  pipelines:
    pl-databricks-exams: ${include.resources/pl-databricks-exams.yaml}
  databricks_jobs:
    job-databricks-exams: ${include.resources/job-databricks-exams.yaml}
  databricks_vectorsearchendpoints:
    vse-databricks-exams:
      name: databricks-exams
  databricks_vectorsearchindexes: ${include.resources/vectorsearchindexes.yaml}

environments:
  debug:
    variables:
      env: dev
  dev:
    variables:
      env: dev
      is_dev: true
  prd:
    variables:
      env: prd
      is_dev: false
